version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5433:1433"
    volumes:
      - ~/apps/mssql/data:/var/lib/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperPassword123

  rabbitMQ:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672

  seq:
    image: datalust/seq:latest
    volumes:
      - ~/apps/seq/data2:/data
    ports:
      - '5341:80'
    environment:
      - ACCEPT_EULA=Y
    networks:
      - gateway-network

networks:
  gateway-network:
    name: gateway-network